# Generated by Django 4.2.11 on 2025-04-10 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('code', models.CharField(default='New', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Thesis', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UrlDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=400)),
                ('authors', models.JSONField(default=list)),
                ('year', models.CharField(default='2024', max_length=4)),
                ('is_visible', models.BooleanField(default=True)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('visualizations', models.IntegerField(default=1)),
                ('url', models.URLField(default='https://example.com')),
                ('description', models.CharField(default='Este documento fue realizado en la era previa al calendario B del 2024, sin embargo puedes analizar su descripción leyendo la introducción del documento, seguramente te pueda ser de mucha utilidad.', max_length=400)),
                ('carrer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='documents.carrer')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documenttype')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentstage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=400)),
                ('authors', models.JSONField(default=list)),
                ('year', models.CharField(default='2024', max_length=4)),
                ('is_visible', models.BooleanField(default=True)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('visualizations', models.IntegerField(default=1)),
                ('file', models.FileField(upload_to='files/')),
                ('description', models.CharField(default="This document is actually pretty awesome and the author doesn't want to steal you the surprise of discovery its content.", max_length=400)),
                ('carrer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='documents.carrer')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documenttype')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentstage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
