# Generated by Django 4.2.11 on 2024-07-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Thesis', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(default='Untitled', max_length=400)),
                ('authors', models.JSONField(default=list)),
                ('year', models.CharField(default='0000', max_length=4)),
                ('url', models.URLField(default='https://example.com')),
                ('is_visible', models.BooleanField(default=True)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('carrer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='documents.carrer')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documenttype')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentstage')),
            ],
        ),
    ]
