# Generated by Django 4.2.11 on 2025-04-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrer',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='filedocument',
            name='title',
            field=models.CharField(default='Untitled', max_length=600),
        ),
        migrations.AlterField(
            model_name='filedocument',
            name='year',
            field=models.CharField(default='2024', max_length=10),
        ),
        migrations.AlterField(
            model_name='urldocument',
            name='description',
            field=models.CharField(default='Este documento fue realizado en la era previa al calendario B del 2024, sin embargo puedes analizar su descripción leyendo la introducción del documento, seguramente te pueda ser de mucha utilidad.', max_length=500),
        ),
        migrations.AlterField(
            model_name='urldocument',
            name='title',
            field=models.CharField(default='Untitled', max_length=600),
        ),
        migrations.AlterField(
            model_name='urldocument',
            name='year',
            field=models.CharField(default='2024', max_length=10),
        ),
    ]
