# Generated by Django 4.2.11 on 2024-07-15 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='documentstage',
            name='name',
        ),
        migrations.AddField(
            model_name='document',
            name='authors',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='code',
            field=models.CharField(default='UnknownCode', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='documentstage',
            name='stage',
            field=models.CharField(default='Finished', max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documenttype'),
        ),
        migrations.AlterField(
            model_name='document',
            name='progress_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='document',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentstage'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(default='Thesis', max_length=50),
        ),
        migrations.DeleteModel(
            name='DocumentStatus',
        ),
    ]
