# Generated by Django 4.2.11 on 2024-07-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentstage',
            name='stage',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
