# Generated by Django 4.2.11 on 2025-04-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_carrer_name_alter_filedocument_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrer',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
