# Generated by Django 4.2.11 on 2024-07-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentstage_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentstage',
            name='stage',
            field=models.CharField(max_length=30),
        ),
    ]
