# Generated by Django 4.2.11 on 2025-04-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_carrer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrer',
            name='name',
            field=models.CharField(max_length=5000),
        ),
    ]
