# Generated by Django 4.2.11 on 2024-08-08 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_newdocument_filedocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedocument',
            name='authors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='carrer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='documents.carrer'),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='code',
            field=models.CharField(default='New', max_length=10),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documenttype'),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='progress_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentstage'),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='title',
            field=models.CharField(default='Untitled', max_length=400),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='year',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AlterField(
            model_name='urldocument',
            name='code',
            field=models.CharField(default='New', max_length=10),
        ),
    ]
