# Generated by Django 4.2.11 on 2025-04-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_carrer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldocument',
            name='url',
            field=models.URLField(default='https://example.com', max_length=900),
        ),
    ]
