# Generated by Django 4.2.11 on 2025-04-16 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_urldocument_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedocument',
            name='carrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.carrer'),
        ),
        migrations.AlterField(
            model_name='urldocument',
            name='carrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.carrer'),
        ),
    ]
