# Generated by Django 4.2.11 on 2024-08-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_carrer_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedocument',
            name='code',
        ),
        migrations.RemoveField(
            model_name='urldocument',
            name='code',
        ),
    ]
