# Generated by Django 4.2.11 on 2024-08-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_filedocument_code_remove_urldocument_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedocument',
            name='description',
            field=models.CharField(default="This document is actually pretty awesome and the author doesn't want to steal you the surprise of discovery its content.", max_length=400),
        ),
        migrations.AlterField(
            model_name='filedocument',
            name='year',
            field=models.CharField(default='2024', max_length=4),
        ),
        migrations.AlterField(
            model_name='urldocument',
            name='year',
            field=models.CharField(default='2024', max_length=4),
        ),
    ]
