# Generated by Django 4.2.11 on 2024-08-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_filedocument_description_alter_filedocument_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldocument',
            name='description',
            field=models.CharField(default="This document is actually pretty awesome and the author doesn't want to steal you the surprise of discovery its content.", max_length=400),
        ),
    ]
