# Generated by Django 4.2.11 on 2024-08-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_urldocument_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldocument',
            name='description',
            field=models.CharField(default='Este documento fue realizado en la era previa al calendario B del 2024, sin embargo puedes analizar su descripción leyendo la introducción del documento, seguramente te pueda ser de mucha utilidad.', max_length=400),
        ),
    ]
