# Generated by Django 4.2.11 on 2024-07-15 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_document_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='carrer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='documents.carrer'),
        ),
    ]
