# Generated by Django 4.2.11 on 2024-10-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_urldocument_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedocument',
            name='visualizations',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='urldocument',
            name='visualizations',
            field=models.IntegerField(default=1),
        ),
    ]
