# Generated by Django 4.2.11 on 2024-07-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_remove_document_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='authors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='Untitled', max_length=400),
        ),
    ]
