version: '3.3'

services:
  backend:
    build: ./Project

    environment:
      DB_HOST: db

    ports:
      - "8001:8000"
    volumes:
      - ./Project:/app
    depends_on:
      - db

     
    

  frontend:
    build: ./thesistrakfront
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: npm start

  db:
    image: mysql:8 # o postgres, según lo que uses
    restart: always
    environment:
      MYSQL_DATABASE: thesis_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "5432:5432"
