# Generated by Django 4.2.11 on 2024-05-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(default='Description', max_length=500),
        ),
    ]
