# Generated by Django 4.2.11 on 2024-06-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_document_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Thesis', max_length=255)),
                ('description', models.CharField(default='Upgrading the world', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='Documents.documenttype'),
        ),
    ]
