# Generated by Django 4.2.11 on 2024-06-08 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Documents', '0004_remove_document_user_document_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='users',
            field=models.ManyToManyField(null=True, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
