# Generated by Django 4.2.11 on 2024-06-08 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Documents', '0005_alter_document_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='users',
            field=models.ManyToManyField(blank=True, max_length=2, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='a', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
