# Generated by Django 4.2.11 on 2024-06-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0006_alter_document_users_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Aaa',
            field=models.ManyToManyField(blank=True, to='Documents.a'),
        ),
    ]
