# Generated by Django 4.2.11 on 2024-06-08 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Documents', '0008_remove_document_aaa_delete_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
