server {
    listen 8000;
    server_name localhost;
    client_max_body_size 50M;  # ⬅️ Esta línea es clave

    # Rutas generales: proxy para el backend de Django
    location / {
        proxy_pass http://thesis_track_backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Rutas para administración o archivos estáticos, según convenga
    location /admin/ {
        proxy_pass http://thesis_track_backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /media/ {
        alias /app/media/;
        autoindex on;
    }

}
