# Generated by Django 4.2.11 on 2024-07-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
