# Generated by Django 4.2.11 on 2025-02-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
