# Generated by Django 4.2.11 on 2024-07-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userz', '0002_account_last_login_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='last_login_ip',
            new_name='IpAdress',
        ),
    ]
