# Generated by Django 4.2.11 on 2025-02-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userz', '0002_account_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
