# Generated by Django 4.2.11 on 2025-04-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userz', '0002_account_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='UserType',
        ),
    ]
