# Generated by Django 4.2.11 on 2025-04-14 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userz', '0003_remove_account_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='UserType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='userz.usertype'),
        ),
    ]
