# Generated by Django 4.2.11 on 2024-07-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userz', '0003_rename_last_login_ip_account_ipadress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='IpAdress',
        ),
    ]
