# Generated by Django 4.2.11 on 2024-07-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userz', '0004_remove_account_ipadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='comments_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='documents_downloaded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='documents_uploaded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='feedback_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='stars_given',
            field=models.IntegerField(default=0),
        ),
    ]
