# Generated by Django 4.2.11 on 2024-07-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userz', '0006_reward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
