# Generated by Django 4.2.11 on 2025-04-14 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userz', '0007_alter_account_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='UserType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userz.usertype'),
        ),
    ]
