# Generated by Django 4.2.11 on 2024-06-22 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Carrer',
        ),
    ]
