# Generated by Django 4.2.11 on 2024-06-22 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='User_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user_type'),
        ),
    ]
