# Generated by Django 4.2.11 on 2024-06-22 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.profile')),
                ('Docs_Amount', models.IntegerField(default=0)),
            ],
            bases=('users.profile',),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.profile')),
                ('Semester', models.CharField(blank=True, max_length=20)),
                ('Docs_Amount', models.IntegerField(default=0)),
                ('Carrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.carrer')),
            ],
            bases=('users.profile',),
        ),
    ]
